### ISSUE TITLE
Add SVG version

### ISSUE THREAD

**Issue by luishdez** [wobblecode/flat-flags#6]

**Comment by waldyrious** [comment]
@luishdez Maybe add a `wontfix` label to the issues you've closed without resolution? I mean this one, #1 and #5 (and possibly others I might not be aware of).

**Comment by luishdez** [comment]
@waldyrious Sure, I'm updating the readme because there are other libraries more suitable for nowadays. Thanks for the recommendation 👍

**Comment by luishdez** [comment]
Won't fix this, since I can't give time to this project PRs/Colabs are always welcome
