### ISSUE TITLE
Wrong flag for Cyprus

### ISSUE THREAD

**Issue by chrierl** [wobblecode/flat-flags#8]
The flag currently used for Cyprus is actually the flag for "Turkish Republic of Northern Cyprus", which is a self-declared state only recognised by Turkey.
The Cyprus flag can be found at https://en.wikipedia.org/wiki/Cyprus, attached in png format below.

![flag_of_cyprus](https://user-images.githubusercontent.com/29948550/27910118-057a8592-6254-11e7-9c0f-9593f84a9309.png)

Thanks!

**Comment by luishdez** [comment]
Hi thanks for the info! I'll update this asap

**Comment by chrierl** [comment]
Brilliant. Thanks!
